### ISSUE TITLE
The surface slowly gets out of sight as you zoom

### ISSUE THREAD

**Issue by AngusLeung96** [tamaskis/planet3D-MATLAB#1]
Awesome high res render of the earth! Just wondering is there a way to prevent the 'sides' of the Earth from disappearing when you zoom in? I'm assuming this has something to do with the way the surface is created and it is 'out of the dimensions' of the viewing box or some sort. Thank you!
![Capture](https://user-images.githubusercontent.com/48578421/139790864-1a90b50c-cb64-4727-a4e9-6a47692fa6c9.JPG)

**Comment by AngusLeung96** [comment]
Never mind! Solved it by setting clipping in matlab off

**Comment by tamaskis** [comment]
Thanks for noticing this. I just updated the function so that clipping is off by default
