### ISSUE TITLE
It is impossible to switch units from meters to kilometers 

### ISSUE THREAD

**Issue by alifly1000** [tamaskis/planet3D-MATLAB#2]
I tried switching the units of the earth to km using by writing 
planet3D('Earth','km')
on Matlab but it doesn't work as it keeps the units in meters

**Comment by tamaskis** [comment]
The `opts` input is a struct. Something like

```matlab
plot_opts.units = 'km'
planet3D('Earth',plot_opts)
```

should work.

**Comment by alifly1000** [comment]
Thank you

Il giorno mer 23 nov 2022 alle 15:54 Tamas Kis ***@***.***>
ha scritto:
